package com.swd.websiteadmin.bean;

public class NewsColumn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_column.columnId
     *
     * @mbggenerated
     */
    private Integer columnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_column.columnName
     *
     * @mbggenerated
     */
    private String columnname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_column.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_column.columnId
     *
     * @return the value of news_column.columnId
     *
     * @mbggenerated
     */
    public Integer getColumnid() {
        return columnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_column.columnId
     *
     * @param columnid the value for news_column.columnId
     *
     * @mbggenerated
     */
    public void setColumnid(Integer columnid) {
        this.columnid = columnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_column.columnName
     *
     * @return the value of news_column.columnName
     *
     * @mbggenerated
     */
    public String getColumnname() {
        return columnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_column.columnName
     *
     * @param columnname the value for news_column.columnName
     *
     * @mbggenerated
     */
    public void setColumnname(String columnname) {
        this.columnname = columnname == null ? null : columnname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_column.state
     *
     * @return the value of news_column.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_column.state
     *
     * @param state the value for news_column.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}