package com.swd.websiteadmin.bean;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class NewsArticle implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_article.articleId
     *
     * @mbggenerated
     */
    private String articleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_article.articleTitle
     *
     * @mbggenerated
     */
    private String articletitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_article.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_article.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_article.releaseTime
     *
     * @mbggenerated
     */
    private Date releasetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_article.deleteTime
     *
     * @mbggenerated
     */
    private Date deletetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_article.columnId
     *
     * @mbggenerated
     */
    private Integer columnid;

    private String columnname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_article.articleSort
     *
     * @mbggenerated
     */
    private Integer articlesort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_article.thumbnail
     *
     * @mbggenerated
     */
    private String thumbnail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_article.articleUrl
     *
     * @mbggenerated
     */
    private String articleurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_article.articleContext
     *
     * @mbggenerated
     */
    private String articlecontext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_article.introduction
     *
     * @mbggenerated
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_article.articleId
     *
     * @return the value of news_article.articleId
     *
     * @mbggenerated
     */
    public String getArticleid() {
        return articleid;
    }

    public String getColumnname() {
        return columnname;
    }

    public void setColumnname(String columnname) {
        this.columnname = columnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_article.articleId
     *
     * @param articleid the value for news_article.articleId
     *
     * @mbggenerated
     */
    public void setArticleid(String articleid) {
        this.articleid = articleid == null ? null : articleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_article.articleTitle
     *
     * @return the value of news_article.articleTitle
     *
     * @mbggenerated
     */
    public String getArticletitle() {
        return articletitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_article.articleTitle
     *
     * @param articletitle the value for news_article.articleTitle
     *
     * @mbggenerated
     */
    public void setArticletitle(String articletitle) {
        this.articletitle = articletitle == null ? null : articletitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_article.state
     *
     * @return the value of news_article.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_article.state
     *
     * @param state the value for news_article.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_article.createTime
     *
     * @return the value of news_article.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_article.createTime
     *
     * @param createtime the value for news_article.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_article.releaseTime
     *
     * @return the value of news_article.releaseTime
     *
     * @mbggenerated
     */
    public Date getReleasetime() {
        return releasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_article.releaseTime
     *
     * @param releasetime the value for news_article.releaseTime
     *
     * @mbggenerated
     */
    public void setReleasetime(Date releasetime) {
        this.releasetime = releasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_article.deleteTime
     *
     * @return the value of news_article.deleteTime
     *
     * @mbggenerated
     */
    public Date getDeletetime() {
        return deletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_article.deleteTime
     *
     * @param deletetime the value for news_article.deleteTime
     *
     * @mbggenerated
     */
    public void setDeletetime(Date deletetime) {
        this.deletetime = deletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_article.columnId
     *
     * @return the value of news_article.columnId
     *
     * @mbggenerated
     */
    public Integer getColumnid() {
        return columnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_article.columnId
     *
     * @param columnid the value for news_article.columnId
     *
     * @mbggenerated
     */
    public void setColumnid(Integer columnid) {
        this.columnid = columnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_article.articleSort
     *
     * @return the value of news_article.articleSort
     *
     * @mbggenerated
     */
    public Integer getArticlesort() {
        return articlesort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_article.articleSort
     *
     * @param articlesort the value for news_article.articleSort
     *
     * @mbggenerated
     */
    public void setArticlesort(Integer articlesort) {
        this.articlesort = articlesort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_article.thumbnail
     *
     * @return the value of news_article.thumbnail
     *
     * @mbggenerated
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_article.thumbnail
     *
     * @param thumbnail the value for news_article.thumbnail
     *
     * @mbggenerated
     */
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail == null ? null : thumbnail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_article.articleUrl
     *
     * @return the value of news_article.articleUrl
     *
     * @mbggenerated
     */
    public String getArticleurl() {
        return articleurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_article.articleUrl
     *
     * @param articleurl the value for news_article.articleUrl
     *
     * @mbggenerated
     */
    public void setArticleurl(String articleurl) {
        this.articleurl = articleurl == null ? null : articleurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_article.articleContext
     *
     * @return the value of news_article.articleContext
     *
     * @mbggenerated
     */
    public String getArticlecontext() {
        return articlecontext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_article.articleContext
     *
     * @param articlecontext the value for news_article.articleContext
     *
     * @mbggenerated
     */
    public void setArticlecontext(String articlecontext) {
        this.articlecontext = articlecontext == null ? null : articlecontext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_article.introduction
     *
     * @return the value of news_article.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_article.introduction
     *
     * @param introduction the value for news_article.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }
}