package com.swd.websiteadmin.bean;

public class NewsArticlePictures {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_article_pictures.picturesId
     *
     * @mbggenerated
     */
    private String picturesid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_article_pictures.picturesName
     *
     * @mbggenerated
     */
    private String picturesname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_article_pictures.picturesUrl
     *
     * @mbggenerated
     */
    private String picturesurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_article_pictures.picturesSort
     *
     * @mbggenerated
     */
    private Integer picturessort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_article_pictures.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_article_pictures.articleId
     *
     * @mbggenerated
     */
    private String articleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_article_pictures.picturesId
     *
     * @return the value of news_article_pictures.picturesId
     *
     * @mbggenerated
     */
    public String getPicturesid() {
        return picturesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_article_pictures.picturesId
     *
     * @param picturesid the value for news_article_pictures.picturesId
     *
     * @mbggenerated
     */
    public void setPicturesid(String picturesid) {
        this.picturesid = picturesid == null ? null : picturesid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_article_pictures.picturesName
     *
     * @return the value of news_article_pictures.picturesName
     *
     * @mbggenerated
     */
    public String getPicturesname() {
        return picturesname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_article_pictures.picturesName
     *
     * @param picturesname the value for news_article_pictures.picturesName
     *
     * @mbggenerated
     */
    public void setPicturesname(String picturesname) {
        this.picturesname = picturesname == null ? null : picturesname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_article_pictures.picturesUrl
     *
     * @return the value of news_article_pictures.picturesUrl
     *
     * @mbggenerated
     */
    public String getPicturesurl() {
        return picturesurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_article_pictures.picturesUrl
     *
     * @param picturesurl the value for news_article_pictures.picturesUrl
     *
     * @mbggenerated
     */
    public void setPicturesurl(String picturesurl) {
        this.picturesurl = picturesurl == null ? null : picturesurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_article_pictures.picturesSort
     *
     * @return the value of news_article_pictures.picturesSort
     *
     * @mbggenerated
     */
    public Integer getPicturessort() {
        return picturessort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_article_pictures.picturesSort
     *
     * @param picturessort the value for news_article_pictures.picturesSort
     *
     * @mbggenerated
     */
    public void setPicturessort(Integer picturessort) {
        this.picturessort = picturessort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_article_pictures.state
     *
     * @return the value of news_article_pictures.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_article_pictures.state
     *
     * @param state the value for news_article_pictures.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_article_pictures.articleId
     *
     * @return the value of news_article_pictures.articleId
     *
     * @mbggenerated
     */
    public String getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_article_pictures.articleId
     *
     * @param articleid the value for news_article_pictures.articleId
     *
     * @mbggenerated
     */
    public void setArticleid(String articleid) {
        this.articleid = articleid == null ? null : articleid.trim();
    }
}