package com.swd.websiteadmin.bean;

import java.util.Date;

public class Position {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.positionId
     *
     * @mbggenerated
     */
    private Integer positionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.positionName
     *
     * @mbggenerated
     */
    private String positionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.workPlace
     *
     * @mbggenerated
     */
    private String workplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.positionMajor
     *
     * @mbggenerated
     */
    private String positionmajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.numbers
     *
     * @mbggenerated
     */
    private Integer numbers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.positionDuty
     *
     * @mbggenerated
     */
    private String positionduty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.qualification
     *
     * @mbggenerated
     */
    private String qualification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.xueli
     *
     * @mbggenerated
     */
    private String xueli;



    private Integer positionsort;

    public Integer getPositionsort() {
        return positionsort;
    }

    public void setPositionsort(Integer positionsort) {
        this.positionsort = positionsort;
    }

    private Integer columnid;

    public Integer getColumnid() {
        return columnid;
    }

    public void setColumnid(Integer columnid) {
        this.columnid = columnid;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.positionId
     *
     * @return the value of position.positionId
     *
     * @mbggenerated
     */
    public Integer getPositionid() {
        return positionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.positionId
     *
     * @param positionid the value for position.positionId
     *
     * @mbggenerated
     */
    public void setPositionid(Integer positionid) {
        this.positionid = positionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.positionName
     *
     * @return the value of position.positionName
     *
     * @mbggenerated
     */
    public String getPositionname() {
        return positionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.positionName
     *
     * @param positionname the value for position.positionName
     *
     * @mbggenerated
     */
    public void setPositionname(String positionname) {
        this.positionname = positionname == null ? null : positionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.workPlace
     *
     * @return the value of position.workPlace
     *
     * @mbggenerated
     */
    public String getWorkplace() {
        return workplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.workPlace
     *
     * @param workplace the value for position.workPlace
     *
     * @mbggenerated
     */
    public void setWorkplace(String workplace) {
        this.workplace = workplace == null ? null : workplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.positionMajor
     *
     * @return the value of position.positionMajor
     *
     * @mbggenerated
     */
    public String getPositionmajor() {
        return positionmajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.positionMajor
     *
     * @param positionmajor the value for position.positionMajor
     *
     * @mbggenerated
     */
    public void setPositionmajor(String positionmajor) {
        this.positionmajor = positionmajor == null ? null : positionmajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.numbers
     *
     * @return the value of position.numbers
     *
     * @mbggenerated
     */
    public Integer getNumbers() {
        return numbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.numbers
     *
     * @param numbers the value for position.numbers
     *
     * @mbggenerated
     */
    public void setNumbers(Integer numbers) {
        this.numbers = numbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.createTime
     *
     * @return the value of position.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.createTime
     *
     * @param createtime the value for position.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.state
     *
     * @return the value of position.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.state
     *
     * @param state the value for position.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.positionDuty
     *
     * @return the value of position.positionDuty
     *
     * @mbggenerated
     */
    public String getPositionduty() {
        return positionduty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.positionDuty
     *
     * @param positionduty the value for position.positionDuty
     *
     * @mbggenerated
     */
    public void setPositionduty(String positionduty) {
        this.positionduty = positionduty == null ? null : positionduty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.qualification
     *
     * @return the value of position.qualification
     *
     * @mbggenerated
     */
    public String getQualification() {
        return qualification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.qualification
     *
     * @param qualification the value for position.qualification
     *
     * @mbggenerated
     */
    public void setQualification(String qualification) {
        this.qualification = qualification == null ? null : qualification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.xueli
     *
     * @return the value of position.xueli
     *
     * @mbggenerated
     */
    public String getXueli() {
        return xueli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.xueli
     *
     * @param xueli the value for position.xueli
     *
     * @mbggenerated
     */
    public void setXueli(String xueli) {
        this.xueli = xueli == null ? null : xueli.trim();
    }
}