package com.swd.websiteadmin.bean;

public class PublicInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publicinfo.publicInfoId
     *
     * @mbggenerated
     */
    private Integer publicinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publicinfo.publicAddress
     *
     * @mbggenerated
     */
    private String publicaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publicinfo.publicFactoryAddress
     *
     * @mbggenerated
     */
    private String publicfactoryaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publicinfo.publicTelephone
     *
     * @mbggenerated
     */
    private String publictelephone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publicinfo.publicInfoId
     *
     * @return the value of publicinfo.publicInfoId
     *
     * @mbggenerated
     */
    public Integer getPublicinfoid() {
        return publicinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publicinfo.publicInfoId
     *
     * @param publicinfoid the value for publicinfo.publicInfoId
     *
     * @mbggenerated
     */
    public void setPublicinfoid(Integer publicinfoid) {
        this.publicinfoid = publicinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publicinfo.publicAddress
     *
     * @return the value of publicinfo.publicAddress
     *
     * @mbggenerated
     */
    public String getPublicaddress() {
        return publicaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publicinfo.publicAddress
     *
     * @param publicaddress the value for publicinfo.publicAddress
     *
     * @mbggenerated
     */
    public void setPublicaddress(String publicaddress) {
        this.publicaddress = publicaddress == null ? null : publicaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publicinfo.publicFactoryAddress
     *
     * @return the value of publicinfo.publicFactoryAddress
     *
     * @mbggenerated
     */
    public String getPublicfactoryaddress() {
        return publicfactoryaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publicinfo.publicFactoryAddress
     *
     * @param publicfactoryaddress the value for publicinfo.publicFactoryAddress
     *
     * @mbggenerated
     */
    public void setPublicfactoryaddress(String publicfactoryaddress) {
        this.publicfactoryaddress = publicfactoryaddress == null ? null : publicfactoryaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publicinfo.publicTelephone
     *
     * @return the value of publicinfo.publicTelephone
     *
     * @mbggenerated
     */
    public String getPublictelephone() {
        return publictelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publicinfo.publicTelephone
     *
     * @param publictelephone the value for publicinfo.publicTelephone
     *
     * @mbggenerated
     */
    public void setPublictelephone(String publictelephone) {
        this.publictelephone = publictelephone == null ? null : publictelephone.trim();
    }
}