package com.swd.websiteadmin.dao;

import com.swd.websiteadmin.bean.NewsArticle;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface NewsArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_article
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String articleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_article
     *
     * @mbggenerated
     */
    int insert(NewsArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_article
     *
     * @mbggenerated
     */
    NewsArticle selectByPrimaryKey(String articleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_article
     *
     * @mbggenerated
     */
    List<NewsArticle> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_article
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NewsArticle record);


    List<NewsArticle> selectForStateAndColumnid(Integer columnid);

    int selectSort();
}