package com.swd.websiteadmin.dao;

import com.swd.websiteadmin.bean.NewsColumn;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface NewsColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_column
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer columnid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_column
     *
     * @mbggenerated
     */
    int insert(NewsColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_column
     *
     * @mbggenerated
     */
    NewsColumn selectByPrimaryKey(Integer columnid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_column
     *
     * @mbggenerated
     */
    List<NewsColumn> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_column
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NewsColumn record);

    List<NewsColumn> selectAllForState();
}