package com.swd.websiteadmin.dao;

import com.swd.websiteadmin.bean.NewsArticlePictures;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface NewsArticlePicturesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_article_pictures
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String picturesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_article_pictures
     *
     * @mbggenerated
     */
    int insert(NewsArticlePictures record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_article_pictures
     *
     * @mbggenerated
     */
    NewsArticlePictures selectByPrimaryKey(String picturesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_article_pictures
     *
     * @mbggenerated
     */
    List<NewsArticlePictures> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_article_pictures
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NewsArticlePictures record);
}