package com.swd.websiteadmin.dao;

import com.swd.websiteadmin.bean.PositionColumn;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface PositionColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_column
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer columnid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_column
     *
     * @mbggenerated
     */
    int insert(PositionColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_column
     *
     * @mbggenerated
     */
    PositionColumn selectByPrimaryKey(Integer columnid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_column
     *
     * @mbggenerated
     */
    List<PositionColumn> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_column
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PositionColumn record);

    List<PositionColumn> selectAllShow();
}