package com.swd.websiteadmin.dao;

import com.swd.websiteadmin.bean.ProductSeason;

import java.util.List;

public interface ProductSeasonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_season
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer seasonid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_season
     *
     * @mbggenerated
     */
    int insert(ProductSeason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_season
     *
     * @mbggenerated
     */
    ProductSeason selectByPrimaryKey(Integer seasonid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_season
     *
     * @mbggenerated
     */
    List<ProductSeason> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_season
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductSeason record);

    List<ProductSeason> selectAllForSeason();
}