package com.swd.websiteadmin.dao;

import com.swd.websiteadmin.bean.ProductPictures;

import java.util.List;

public interface ProductPicturesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pictures
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String picturesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pictures
     *
     * @mbggenerated
     */
    int insert(ProductPictures record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pictures
     *
     * @mbggenerated
     */
    ProductPictures selectByPrimaryKey(String picturesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pictures
     *
     * @mbggenerated
     */
    List<ProductPictures> selectAllForSkus(Integer skusid);

    List<ProductPictures> selectAllForSkustwo(Integer skusid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pictures
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductPictures record);

    List<ProductPictures> selectAllForPictures();


}