package com.swd.websiteadmin.dao;

import com.swd.websiteadmin.bean.PublicInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface PublicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publicinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer publicinfoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publicinfo
     *
     * @mbggenerated
     */
    int insert(PublicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publicinfo
     *
     * @mbggenerated
     */
    PublicInfo selectByPrimaryKey(Integer publicinfoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publicinfo
     *
     * @mbggenerated
     */
    List<PublicInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publicinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PublicInfo record);
}